### ISSUE TITLE
External Drag & Drop doesn't work on Firefox

### ISSUE THREAD

**Issue by Ligthy** [reppners/ngx-drag-drop#35] opened 2018-08-20 11:34 UTC
Hi,

As the title says, drag & drop from an external source doesn't work on Firefox.

You can reproduce by going to the "Native" tab  : https://reppners.github.io/ngx-drag-drop/ 

Thanks.

**Comment by reppners** [comment] 2018-08-25 17:47
Hi, thanks for reporting :) 

I can confirm its not working. Will look into it the next couple of days.

**Comment by jguyenot** [comment] 2018-09-11 15:39
Hello,

i confirm too that in firefox the external source open the file directly onto the page.

In Chrome and Internet Explorer the event.dataTransfert is not populated with the file.
![image](https://user-images.githubusercontent.com/38251050/45370965-a54b8f00-b5e9-11e8-9c75-752da9b5f7c6.png)

**Comment by jguyenot** [comment] 2018-10-18 10:05
Hi, after some study, the problem is with the console.
If i log dataTransfer.files[0] is full.

You can close the issue.

**Comment by bkarv** [comment] 2018-10-27 12:04
Just saw this I have the same issue with Chrome see below
`
https://github.com/reppners/ngx-drag-drop/issues/48`

@jguyenot Did you find a solution?

**Comment by reppners** [comment] 2018-10-27 17:44
Did some research and it might be related to my mistake of not implementing firefox requirements for drag and drop correctly in my demo.

Firefox needs a `dragstart` handler which sets some data on the dataTransfer instance of the event. See https://salesforce.stackexchange.com/a/214639

**Comment by reppners** [comment] 2018-10-27 19:46
Resolved it and released fix with rc.4. You can install with `npm install ngx-drag-drop@next`. It's still on a branch pending confirmation before I'll merge in master.

**Comment by Ligthy** [comment] 2018-11-02 08:48
Hi,
I can confirm that it is now working on Firefox !

Thanks !

**Closed** 2018-11-02 08:54 UTC
Labels: bug, fix-released-await-confirmation
