### ISSUE TITLE
How to replace a list item?

### ISSUE THREAD

**Issue by wendellestradairely** [reppners/ngx-drag-drop#100] opened 2021-11-22 06:39 UTC
How to implement a drag & drop to a list wherein instead of inserting the dragged item between two list items, the existing item in the target list will be replaced when the dragged item is dropped?

![image](https://user-images.githubusercontent.com/50942719/142810231-96eff030-6998-4dbe-81f6-9472fb64745b.png)

**Real-world scenario:**
Here's what my use-case is. The goal is to drag the field from the right to the text field to the left:

![image](https://user-images.githubusercontent.com/50942719/142810307-b94d3b36-1f9a-4820-91e3-268a0f1a7b7e.png)

**Comment by reppners** [comment] 2021-12-22 20:58
Replacing an item in the dropzone instead of adding it is entirely up to the logic that handles the drop.

See https://github.com/reppners/ngx-drag-drop/blob/dee13087197ab7e39f86e1833393e5cd0807fbae/demo/app/list/list.component.ts#L81-L90 for an example of deleting items that are dropped.

**Comment by reppners** [comment] 2021-12-30 14:11
Closing as it is not a bug or new feature. If you need further guidance, let me know by adding a comment!

**Closed by reppners** 2021-12-30 14:11 UTC
Labels: question

**Comment by wendellestradairely** [comment] 2021-12-31 00:49
@reppners Thank you. 😀
