### ISSUE TITLE
ngx-drag-drop Angular 14 update

### ISSUE THREAD

**Issue by asatryanarsen** [reppners/ngx-drag-drop#115] opened 2022-07-09 12:21 UTC
Hi all contributors, 

I appreciate all the work that you have done, it is really helping me a lot in my projects.

I am interested if you are planning to update the project to support angular 14, and if yes what are the timelines for that

**Comment by reppners** [comment] 2022-07-13 07:22
Hi, is there a breaking change from v13.x to v14.x for the library? There will be a v14.x release but it should be possible to just use the v13 version of this module.

**Comment by reppners** [comment] 2022-07-27 18:45
I see. Will try to cut a v14 release this week. 👍

**Comment by NOPR9D** [comment] 2022-08-06 04:55
![](https://media.giphy.com/media/3o6YfZq549Im6wjlXW/giphy.gif)

**Comment by NOPR9D** [comment] 2022-08-06 22:10
> I see. Will try to cut a v14 release this week. 👍

i any help, i can
will be the occasion to learn how update a library

**Comment by raghavendra5k** [comment] 2022-08-25 22:14
update for Angular v14 release please

**Comment by reppners** [comment] 2022-08-26 19:07
finally got around to do this.. thanks for your patience!

Let me know if the issue is not resolved by the v14 release, will reopen if that would be the case!

**Closed by reppners** 2022-08-26 19:07 UTC
